//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html

using Dapper.Contrib.Extensions;

namespace DAL.Models
{
    public class Payments
    {
        [Key]
        public int Id { get; set; }


        public int PayableItemId { get; set; }


        public decimal PaidAmount { get; set; }


        public int ReportingPeriodId { get; set; }


        public int PaymentApplicationId { get; set; }

    }
}